### ISSUE TITLE
微信分享bitmap问题

### ISSUE THREAD

**Issue by kaleai** [lingochamp/ShareLoginLib#4]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@154d8e1d
            at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1282)
            at android.graphics.Canvas.drawBitmap(Canvas.java:1369)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:740)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:634)
            **at com.liulishuo.share.util.ShareUtil.extractThumbNail(ShareUtil.java:95)**
            at com.liulishuo.share.wechat.WechatShareManager.shareWebPage(WechatShareManager.java:118)
            at com.liulishuo.share.wechat.WechatShareManager.share(WechatShareManager.java:190)
            at com.duitang.main.MainActivity$1.onClick(MainActivity.java:55)
            at android.view.View.performClick(View.java:4781)
            at android.view.View$PerformClick.run(View.java:19874)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
07-24 00:13:59.412  10900-10900/com.duitang.main E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.duitang.main, PID: 10900
    java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@154d8e1d
            at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1282)
            at android.graphics.Canvas.drawBitmap(Canvas.java:1369)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:740)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:634)
            at com.liulishuo.share.util.ShareUtil.extractThumbNail(ShareUtil.java:95)
            at com.liulishuo.share.wechat.WechatShareManager.shareWebPage(WechatShareManager.java:118)
            at com.liulishuo.share.wechat.WechatShareManager.share(WechatShareManager.java:190)
            at com.duitang.main.MainActivity$1.onClick(MainActivity.java:55)
            at android.view.View.performClick(View.java:4781)
            at android.view.View$PerformClick.run(View.java:19874)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

line:95
---->
            if (crop) {
                final Bitmap cropped = Bitmap.createBitmap(bm, (bm.getWidth() - width) >> 1, (bm.getHeight() - height) >> 1, width, height);
                if (cropped == null) {
                    return bm;
                }
这里用的应该是微信的demo中的一个图片压缩算法，可能有点问题。

**Comment by echo-lgtm** [comment]
确实 微信demo方法有问题，你可以参考我weibo里面的写法 @tianzhijiexian

**Comment by echo-lgtm** [comment]
重新发下pull request 吧 刚才看你代码里面好多你们业务有关的diff @tianzhijiexian

**Comment by kaleai** [comment]
pull request 已经被merge了，还需要重新发一次么？

**Comment by echo-lgtm** [comment]
我fix一下吧 @tianzhijiexian

**Comment by kaleai** [comment]
好的，拜托了@echodjb

**Comment by echo-lgtm** [comment]
看来还是需要你更改代码以后再pull request  你现在里面的代码有很多不该提交的

**Comment by kaleai** [comment]
问题是这样的，你原始的工程中没有添加ignore文件，所以我拉下来的工程的所有修改也会全部提交。所以diff的时候就会遇到很多无用的文件的提交信息。

**Comment by kaleai** [comment]
所以希望您能先在原本的项目中添加好ignore，然后我重新拉下来再提交pr(_^__^_) @echodjb

**Comment by echo-lgtm** [comment]
好了 @tianzhijiexian
